# Generated by Django 4.1.4 on 2023-05-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('operator', 'Оператор')], max_length=50),
        ),
    ]
