# Generated by Django 4.1.4 on 2023-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsell',
            name='status',
            field=models.BooleanField(choices=[(True, 'Open - no payed'), (False, 'Closed - payed')], default=True, help_text='True = Open (not payed)'),
        ),
    ]
