# Generated by Django 4.1.4 on 2023-05-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='total_price',
        ),
    ]
