# Generated by Django 4.1.4 on 2023-05-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_productsell_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreAll',
            new_name='Stock',
        ),
    ]
