# Generated by Django 4.1.4 on 2023-05-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_rename_storeall_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsell',
            name='client',
        ),
        migrations.RemoveField(
            model_name='productsell',
            name='table',
        ),
        migrations.AddField(
            model_name='productsell',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='club.order'),
        ),
    ]
