# Generated by Django 4.1.4 on 2023-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_remove_store_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.PositiveBigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
