# Generated by Django 4.1.4 on 2023-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_productsellcheck_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsell',
            old_name='status',
            new_name='pay_status',
        ),
        migrations.AddField(
            model_name='productsell',
            name='play_status',
            field=models.CharField(choices=[('paused', 'Приостоновлена'), ('active', 'Активна'), ('ended', 'Завершена')], default='paused', max_length=50),
        ),
    ]
