# Generated by Django 4.1.4 on 2023-05-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='barcode',
        ),
    ]
