# Generated by Django 4.1.4 on 2023-05-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_rename_status_order_pay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
