# Generated by Django 4.1.4 on 2023-05-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_alter_productlist_name_alter_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='limit',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
