# Generated by Django 4.1.4 on 2023-05-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_order_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
